### ISSUE TITLE
fs.exists method throws

### ISSUE THREAD

**Issue by tvervest** [vigour-io/vigour-fs#15]
When calling the `fs.exists` method the following error is thrown;

```
/Users/Thomas/Desktop/bug/node_modules/vigour-fs/lib/server.js:419
  if (_cb.length === 2) {
         ^

TypeError: Cannot read property 'length' of undefined
    at Object.exports.exists (/Users/Thomas/Desktop/bug/node_modules/vigour-fs/lib/server.js:419:10)
    at Object.<anonymous> (/Users/Thomas/Desktop/bug/index.js:2:4)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

It's very simple to reproduce with the following script;

```
const fs = require('vigour-fs');
fs.exists('./test.txt').then(console.log);
```

The problem is caused because no callback parameter is passed to the `exists` method. However, seeing how the method is supposed to return a Promise, this should not be an issue.

**Comment by shawninder** [comment]
vigour-fs expects callbacks and doesn't return promises. If you want promises, use vigour-fs-promised and add `Async` to the end of the function you're using. For example:

```
const fs = require('vigour-fs-promised');
fs.existsAsync('./test.txt').then(console.log);
```

should work as expected.

If this is indeed the case, please close the issue :)

**Comment by shawninder** [comment]
You may be looking at an old script that predates vigour-fs-promised. In those days I would do something like this:

```
var Promise = require('promise')
var fs = require('vigour-fs')
var _exists = Promise.denodeify(fs.exists)
_exists('./test.txt').then(console.log);
```

See https://github.com/then/promise#promisedenodeifyfn

**Comment by tvervest** [comment]
Two points;
1) my bad, I should have been using `vigour-fs-promised` 👍
2) the method doesn't check if a callback is set, but it does check the `length` property (???)

Should we just do a null check on [lib/server.js:419](https://github.com/vigour-io/fs/blob/master/lib/server.js#L419)?

**Comment by shawninder** [comment]
1) 👍 
2) the `length` thing allows us to support both `fs.exists(function (exists) {...})` (same API as node's `fs` module) and `fs.exists(function (err, exists) {...})`, which allows Bluebird to convert `exists` to a promise-returning function in `vigour-fs-promised` (it also allows `Promise.denodeify` to work for this function just like it works for the other node-style-callback functions)

So no, a null check would not be sufficient.

**Comment by tvervest** [comment]
okily dokily, clodsing this issue then
